
export const UI_TEXT = {
  en: {
    appTitle: "Westminster Shorter Catechism",
    browse: "Browse",
    quiz: "Quiz",
    searchPlaceholder: "Search questions...",
    questionLabel: "Question",
    answerLabel: "Answer",
    scripturesLabel: "Scriptural Proofs",
    showAnswer: "Reveal Answer",
    hideAnswer: "Hide Answer",
    nextQuestion: "Next Question",
    prevQuestion: "Previous",
    gotIt: "I Knew It",
    missedIt: "Review Later",
    quizComplete: "Session Complete",
    quizIntro: "Test your knowledge. Read the question, recite the answer, then check your accuracy.",
    startQuiz: "Start Quiz",
    restart: "Start Over",
    mastery: "Mastery",
    questionId: "Q",
    viewScriptures: "View Scriptures",
    hideScriptures: "Hide Scriptures",
    saved: "Saved",
    viewAll: "View All",
    emptySaved: "No saved questions yet. Tap the star icon to bookmark questions for later study.",
    proofReference: "Proof Reference",
    tabToReviewAnswer: "Tap to Reveal Answer",
    answer: "Answer",
    question: "Question",
    correctOf: "correct out of",
    questions: "Questions"
  },
  zh: {
    appTitle: "威斯敏斯特小要理问答",
    browse: "浏览",
    quiz: "测验",
    searchPlaceholder: "搜索问题...",
    questionLabel: "问题",
    answerLabel: "回答",
    scripturesLabel: "经文引证",
    showAnswer: "显示答案",
    hideAnswer: "隐藏答案",
    nextQuestion: "下一题",
    prevQuestion: "上一题",
    gotIt: "记住了",
    missedIt: "需复习",
    quizComplete: "本次学习结束",
    quizIntro: "测试你的知识。阅读问题，背诵答案，然后检查准确性。",
    startQuiz: "开始测验",
    restart: "重新开始",
    mastery: "掌握程度",
    questionId: "问",
    viewScriptures: "查看经文",
    hideScriptures: "隐藏经文",
    saved: "已收藏",
    viewAll: "查看全部",
    emptySaved: "暂无收藏问题。点击星号图标收藏问题以便日后学习。",
    proofReference: "证明经文",
    tabToReviewAnswer: "点击查看答案",
    answer: "答案",
    question: "问题",
    correctOf: "正确/总计",
    questions: "个问题"
  }
};